#!/usr/bin/env python3
import argparse
import sys
from db import init_db, add_default_config, add_job, gen_id, list_jobs, get_counts

def cmd_hello():
    print("✅ queuectl is set up successfully!")
    print("Run `python queuectl.py --help` to see available commands (we’ll add more soon).")

def cmd_initdb():
    init_db()
    add_default_config()

def cmd_enqueue(args):
    job_id = args.id or gen_id()
    if not args.command:
        print("Error: --command is required for enqueue", file=sys.stderr)
        sys.exit(2)
    try:
        add_job(job_id, args.command, args.max_retries)
        print(f"✅ Enqueued job {job_id}")
    except Exception as e:
        print("Failed to enqueue job:", e, file=sys.stderr)
        sys.exit(1)

def cmd_list(args):
    rows = list_jobs(state=args.state)
    if not rows:
        print("No jobs found.")
        return
    for r in rows:
        print(f"- id: {r['id']}")
        print(f"  command: {r['command']}")
        print(f"  state: {r['state']}")
        print(f"  attempts: {r['attempts']}")
        print(f"  max_retries: {r['max_retries']}")
        print(f"  created_at: {r['created_at']}")
        print()

def cmd_status(_args):
    counts = get_counts()
    print("Job counts:")
    for s in ("pending","processing","completed","failed","dead"):
        print(f"  {s}: {counts.get(s,0)}")

def main():
    parser = argparse.ArgumentParser(prog='queuectl', description='queuectl - background job queue CLI')
    subparsers = parser.add_subparsers(dest='subcommand')

    subparsers.add_parser('hello', help='Simple test command')
    subparsers.add_parser('initdb', help='Initialize the SQLite database')

    p_enq = subparsers.add_parser('enqueue', help='Enqueue a new job')
    p_enq.add_argument('--id', type=str, help='Job id (optional, autogenerated if omitted)')
    p_enq.add_argument('--command', type=str, help='Shell command to run (required)')
    p_enq.add_argument('--max-retries', type=int, default=3, help='Maximum retries for the job')

    p_list = subparsers.add_parser('list', help='List jobs')
    p_list.add_argument('--state', type=str, choices=['pending','processing','completed','failed','dead'], help='Filter by state')

    subparsers.add_parser('status', help='Show job counts by state')

    args = parser.parse_args()

    if args.subcommand == 'hello':
        cmd_hello()
    elif args.subcommand == 'initdb':
        cmd_initdb()
    elif args.subcommand == 'enqueue':
        cmd_enqueue(args)
    elif args.subcommand == 'list':
        cmd_list(args)
    elif args.subcommand == 'status':
        cmd_status(args)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
